apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb2
  template:
    metadata:
      labels:
        app: myweb2
    spec:
      containers:
      - name: myweb2
        image: heewon0915/cicdtest:green
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myweb2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mywebfile
